stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  # - deploy gérer par render donc pas stage

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: php:8.2
  script:
    - apt-get update && apt-get install -y git zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - rm composer-setup.php
    #Installe les dépendances Symfony
    - echo "Début de la construction du projet..."
    - composer install --no-scripts --no-interaction
    # Exécute les migrations Symfony (si nécessaire)
    - echo "Installation des dépendances terminée."
    - php bin/console doctrine:migrations:migrate --no-interaction

unit-test-job:   # This job runs in the test stage.
  stage: test  # It only starts when the job in the build stage completes successfully.
  script:
    - php bin/phpunit

