stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  # - deploy gérer par render donc pas stage

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:latest # Install derniere version de node 
  script:
    #Installe les dépendances Symfony
    - composer install --no-scripts --no-interaction
    # Exécute les migrations Symfony (si nécessaire)
    - php bin/console doctrine:migrations:migrate --no-interaction

unit-test-job:   # This job runs in the test stage.
  stage: test  # It only starts when the job in the build stage completes successfully.
  script:
    - php bin/phpunit

