# version: '3'

# services:
# ###> doctrine/doctrine-bundle ###
#   database:
#     image: postgres:${POSTGRES_VERSION:-16}-alpine
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB:-app}
#       # You should definitely change the password in production
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#       POSTGRES_USER: ${POSTGRES_USER:-app}
#     volumes:
#       - database_data:/var/lib/postgresql/data:rw
#       # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#       # - ./docker/db/data:/var/lib/postgresql/data:rw
# ###< doctrine/doctrine-bundle ###

# volumes:
# ###> doctrine/doctrine-bundle ###
#   database_data:
# ###< doctrine/doctrine-bundle ###
version: '3'

services:
  database:
    image: mysql:8.0  # Utilise l'image MySQL 8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}  # nom de la base de données
      MYSQL_USER: ${MYSQL_USER:-app}          # utilisateur de la base de données
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test_mdp}  # mot de passe utilisateur
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_password}  # mot de passe root à définir
    ports:
      - "3306:3306"  # expose MySQL sur le port 3306
    volumes:
      - database_data:/var/lib/mysql:rw  # volume de persistance des données MySQL

volumes:
  database_data:
